### ISSUE TITLE
Typo? in knockout detection/refinement

### ISSUE THREAD

**Issue by jan-glx** [asncd/MIMOSCA#3]
Hi Atray,
Is the `+0.5` in 
https://github.com/asncd/MIMOSCA/blob/27199eb9e4aa1655cc469d52dc9ac89fc3bbc3be/mimosca.py#L646
a typo that should read `*0.5` (or even ` ` -- as GENE_var is already computed including a factor 2) ?
best, Jan

**Comment by asncd** [comment]
Hi Jan,

The genes are already filtered for zero variance to avoid division by zero, but division by very small numbers (say a gene that is expressed weakly in one or two cells) can also be an issue. The added 0.5 is a bit of a hack to put a floor on the variance, similar to a pseudocount. A reasonable alternative would be to change `GENE_var>0`  to `GENE_var>constant`.

Let me know if that makes sense.

Best,
Atray

**Comment by jan-glx** [comment]
I see, that makes sense. Thank you for the quick reply! What scale is Y here (has it been for fig. 2H)? Raw/ 10k normalized/ log2(10k+1)?
For the computation of the perturbation probability you assume the residuals for the different genes to be independent, right? Why do you scale with the variance of the genes' expression instead of the variance of each gene's residuals?

**Comment by asncd** [comment]
Log2(Raw + 1).

Great questions! 

yes we make an assumption of independence which is, in most biological contexts violated. Before modeling cell states, it is possible that this leads us to be more confident than we should be in perturbation probabilities. After modeling cell states, the covariance structure should be significantly reduced.  

There are underlying homoscedasticity and normality assumptions in our regression. Under these assumptions, the effect of a perturbation is being modeled as a shift in the mean expression value with the same variance. The perturbation probability is being modeled as the relative likelihood of observing a value given the two theoretical Gaussian distributions predicted by the model.

In practice the two variances you refer to were very correlated for us (see below)
![image](https://user-images.githubusercontent.com/5026473/29720483-0ef3da50-8988-11e7-98d5-09d064b6dc2c.png)

**Comment by krejciadam** [comment]
Hi! 
I have a question along the same lines: Looking at Fig. 4A of the paper, I'm thinking, if the scale of Y is Log2(Raw + 1), it means that beta has the meaning of absolute log expression difference. Wouldn't it make sense to scale Y so that beta would denote relative difference in expression? What I mean is that now, highly expressed genes are likely to get higher beta just because higher absolute differences in expression. Or do I understand this incorrectly? 
Thank you. 
Adam

**Comment by jan-glx** [comment]
@Adam: "What I mean is that now, highly expressed genes are likely to get higher beta just because higher absolute differences in expression."
Yes, but that bias is only relevant for very lowly expressed genes (and result of the pseudo-count)  log(y1+1)-(y2+1)=log((y1+1)/(y2+1)).
Without it, log(y1)-(y2)=log(y1/y2), so the absolute difference of log transformed values is the log transformation of the relative difference. Therefore, without the pseudo count you don't expect highly expressed genes to have higher betas. And since lowly expressed genes exhibit a higher relative (technical) variance, the bias introduced by the pseudo count might even be desired.

@Atray: Thanks for the promt and precise response back then. I wanted to give detailed response on how the isotropy assumption for the Gaussian distribution leads to overconfident estimates that are over-counterbalanced by using the observed variance instead of the residual variance (VAR(y)=VAR(residuals)+VAR(beta)) but then realized that that you did completely over-fit that model and, in reality, confident inference of knockout state is only possible for very few cells (mostly GABPA_9 & YY1_10 cells) and got lost trying to find a better way to infer knockout state. (Now we know that avoiding barcode uncoupling helps a lot). Great work nevertheless!

**Comment by jan-glx** [comment]
Seems like [Papalexi et al. 2021](https://www.nature.com/articles/s41588-021-00778-2) reached a similar conclusion now.

**Comment by asncd** [comment]
Thanks for sharing.

One of our earlier attempts at addressing this problem was to use the out
of bag probabilities from a random forest classifier in which
"non-targeting / control" were used as one class and the cells with a
particular perturbation were used as the other. We ended up with the
approach that was in the paper since it was simple in comparison,
but certainly appreciate the potential for overfitting on weak effects esp.
based on accounting for variance of raw data vs. residuals.
